### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by superdiazzz** [stepanowon/youtube-vue3#3]
I got this issue after implement this script

```
<div v-if="currentDoc" class="section">
			<p class="title">{{currentDoc.subject}}</p>
			{{currentDoc.description}} \\ wGzwhFthnWE
			<div v-if="currentDoc.description">
				<YoutubeVue3 ref="youtube" :videoid="String(currentDoc.description)" :loop="1" :width="600" :height="400"
      				@ended="onEnded" @paused="onPaused" @played="onPlayed"/>
			</div>
			
		</div>
```
It works when harcoded but not works when variable mode.  That error keep continue like performed looping infinity
![Screen Shot 2022-03-31 at 22 58 07](https://user-images.githubusercontent.com/10770867/161098647-77cfafe7-88b7-46af-9d79-d31ba20af584.png)

**Comment by stepanowon** [comment]
I fixed the problem by rebuilding. please try again. If you find the same problem, please post an issue.

**Comment by superdiazzz** [comment]
> 

How do you rebuild? still not work for me
